# Generated by Django 4.0.3 on 2022-04-13 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_center', models.CharField(max_length=100, verbose_name='Образовательный центр')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
                ('start_education', models.DateField(verbose_name='Дата начала')),
                ('finish_education', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя')),
                ('summary_position', models.CharField(max_length=100, verbose_name='Должность')),
                ('category', models.CharField(choices=[('Information technology', 'Информационные технологии'), ('Medicine', 'Медецина'), ('Marketing', 'Маркетинг'), ('Sales', 'Продажи'), ('Production', 'Производство'), ('Insurance', 'Страхование')], max_length=50, verbose_name='Категория вакансии')),
                ('salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='Заработная плата')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('telegram', models.URLField(max_length=500, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True, verbose_name='Linkedin')),
                ('publication', models.BooleanField(verbose_name='Публикация резюме')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('education', models.ManyToManyField(blank=True, related_name='summary_education', to='app.education')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('work_position', models.CharField(max_length=100, verbose_name='Должность')),
                ('responsibilities', models.TextField(max_length=3000, verbose_name='Обязанности')),
                ('start_work', models.DateField(verbose_name='Дата начала')),
                ('finish_work', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_work_experience', to='app.summary')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='app.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='app.education')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_education', to='app.summary')),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='work_experience',
            field=models.ManyToManyField(blank=True, related_name='summary_experience', to='app.workexperience'),
        ),
    ]
