# Generated by Django 4.0.3 on 2022-04-15 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_summaryworkexperience_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_position', models.CharField(max_length=100, verbose_name='Должность')),
                ('category', models.CharField(choices=[('Information technology', 'Информационные технологии'), ('Medicine', 'Медецина'), ('Marketing', 'Маркетинг'), ('Sales', 'Продажи'), ('Production', 'Производство'), ('Insurance', 'Страхование')], max_length=50, verbose_name='Категория вакансии')),
                ('salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='Заработная плата')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание вакансии')),
                ('work_experience_from', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)], verbose_name='Заработная плата от')),
                ('work_experience_to', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Заработная плата до')),
                ('publication', models.BooleanField(verbose_name='Публикация вакансии')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
