# Generated by Django 4.0.3 on 2022-04-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_applicant', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_employer', to=settings.AUTH_USER_MODEL, verbose_name='Работадатель')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_summary', to='app.summary', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_vacancy', to='app.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('responce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messeges_response', to='app.response', verbose_name='Отклик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
