# Generated by Django 4.0.3 on 2022-04-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='responce',
            new_name='response',
        ),
    ]
